Zt 101 rma sale fix#4
sovannarith-keo/rmacambodia pull request #51
Opened 2022-05-24 08:28 UTC by zatinrma

https://trello.com/c/MmhZ8XIc/235-action-button-create-po-in-form-view-vsb
https://trello.com/c/f3Y1QD8Y/237-fix-field-delivery-to-in-wizard-form-create-po-from-vsb

2022-05-24 08:36 UTC, panharithrma requested changes

2022-05-24 08:36 UTC, panharithrma commented on rma_vsb/wizard/rma_vsb_order_wizard.py
> +        if self._context.get('create_po_from_one_vsb_rec'):
no need to use context, I think

2022-05-24 08:36 UTC, panharithrma commented on rma_vsb/wizard/rma_vsb_order_wizard.py
> +                    if not vsb_line.lot_serial_number or not vsb_line.engine:
use function all() to increase performance and cleaner code

2022-05-24 08:59 UTC, zatinrma commented on rma_vsb/wizard/rma_vsb_order_wizard.py
> +        if self._context.get('create_po_from_one_vsb_rec'):
2 Different Action

2022-05-25 01:21 UTC, panharithrma requested changes

2022-05-25 01:21 UTC, panharithrma commented on rma_vsb/wizard/rma_vsb_order_wizard.py
> +        for line in self._context.get('vsb_order_line'):
change to self._context.get('vsb_order_line', [])

2022-05-25 01:21 UTC, panharithrma commented on rma_vsb/wizard/rma_vsb_order_wizard.py
> +            'default_order_line': self._context.get('vsb_order_line'),
change to self._context.get('vsb_order_line', [])

2022-05-25 01:30 UTC, merged